name: vita_bella
description: A new Flutter project.

publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Gothic
      fonts:
        - asset: assets/fonts/GothicA1-Regular.ttf
        - asset: assets/fonts/GothicA1-Bold.ttf

  uses-material-design: true

   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
